import '../headersFooters/commonBlocks/commonLogoCircle/commonLogoCircle.js';
import './commonBlocks/dropdown/dropdown.js';
import './commonBlocks/checkboxButtons/checkboxButtons.js';
import './commonBlocks/radioButtons/radioButtons.js';
import './commonBlocks/toggle/toggle.js';
import './commonBlocks/likeButton/likeButtonColor/likeButtonColor.js';
import './commonBlocks/likeButton/likeButtonGrey/likeButtonGrey.js'
import './commonBlocks/rateButton/rateButton.js';
import './commonBlocks/richCheckboxButtons/richCheckboxButtons.js';
import './commonBlocks/buttons/buttons.js';
import './commonBlocks/guestRecall/guestRecall.js';
import './commonBlocks/bulletList/bulletList.js';
import './formElements.scss';
